# =============================================================================
# OPA External Authorization usando AuthorizationPolicy CUSTOM
# Esta es la forma RECOMENDADA por Istio
#
# IMPORTANTE: Requiere configurar el extensionProvider en el mesh config
# Ver instrucciones al final del archivo
# =============================================================================

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-jwt-policies
  namespace: gateway
  labels:
    app: opa-ext-authz
data:
  policy.rego: |
    package envoy.authz

    import future.keywords.if
    import future.keywords.in

    # Default: denegar
    default allow := {
      "allowed": false,
      "http_status": 401,
      "body": "Authorization required"
    }

    # Sin token
    allow := {
      "allowed": false,
      "http_status": 401,
      "body": "Authorization header required"
    } if {
      not bearer_token
    }

    # Token inválido
    allow := {
      "allowed": false,
      "http_status": 401,
      "body": "Invalid or expired token"
    } if {
      bearer_token
      not is_token_valid
    }

    # Token válido pero sin claims
    allow := {
      "allowed": false,
      "http_status": 403,
      "body": "Missing required claim: foo=bar"
    } if {
      is_token_valid
      not has_required_claims
    }

    # Método no permitido
    allow := {
      "allowed": false,
      "http_status": 405,
      "body": "Method not allowed"
    } if {
      is_token_valid
      has_required_claims
      not is_valid_method
    }

    # Todo válido - PERMITIR
    allow := {
      "allowed": true,
      "headers": {
        "x-user-id": token.payload.sub,
        "x-validated-by": "opa-ext-authz"
      }
    } if {
      is_token_valid
      has_required_claims
      is_valid_method
    }

    # =========================================================================
    # HELPERS
    # =========================================================================

    is_valid_method if {
      input.attributes.request.http.method in ["GET", "POST"]
    }

    is_token_valid if {
      token.valid
      token.payload.iss == "testing@secure.istio.io"
      now := time.now_ns() / 1000000000
      token.payload.exp > now
    }

    has_required_claims if {
      token.payload.foo == "bar"
    }

    token := {"valid": valid, "payload": payload} if {
      [valid, _, payload] := io.jwt.decode_verify(bearer_token, {
        "cert": data.keys.jwks,
        "iss": "testing@secure.istio.io"
      })
    }

    token := {"valid": false, "payload": {}} if {
      not bearer_token
    }

    bearer_token := t if {
      auth_header := input.attributes.request.http.headers.authorization
      startswith(auth_header, "Bearer ")
      t := substring(auth_header, 7, -1)
    }

  data.json: |
    {
      "keys": {
        "jwks": "{\"keys\":[{\"e\":\"AQAB\",\"kid\":\"DHFbpoIUqrY8t2zpA2qXfCmr5VO5ZEr4RzHU_-envvQ\",\"kty\":\"RSA\",\"n\":\"xAE7eB6qugXyCAG3yhh7pkDkT65pHymX-P7KfIupjf59vsdo91bSP9C8H07pSAGQO1MV_xFj9VswgsCg4R6otmg5PV2He95lZdHtOcU5DXIg_pbhLdKXbi66GlVeK6ABZOUW3WYtnNHD-91gVuoeJT_DwtGGcp4ignkgXfkiEm4sw-4sfb4qdt5oLbyVpmW6x9cfa7vs2WTfURiCrBoUqgBo_-4WTiULmmHSGZHOjzwa8WtrtOQGsAFjIbno85jp6MnGGGZPYZbDAa_b3y5u-YpW7ypZrvD8BgtKVjgtQgZhLAGezMt0ua3DRrWnKqTZ0BJ_EyxOGuHJrLsn00fnMQ\"}]}"
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-ext-authz
  namespace: gateway
  labels:
    app: opa-ext-authz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opa-ext-authz
  template:
    metadata:
      labels:
        app: opa-ext-authz
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:0.60.0-envoy
          args:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:8181"
            - "--diagnostic-addr=0.0.0.0:8282"
            - "--set=plugins.envoy_ext_authz_grpc.addr=:9191"
            - "--set=plugins.envoy_ext_authz_grpc.path=envoy/authz/allow"
            - "--set=decision_logs.console=true"
            - "--ignore=.*"
            - "/policies/policy.rego"
            - "/policies/data.json"
          ports:
            - name: grpc
              containerPort: 9191
            - name: http
              containerPort: 8181
            - name: diagnostics
              containerPort: 8282
          volumeMounts:
            - name: policies
              mountPath: /policies
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health?plugins
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health?plugins
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: policies
          configMap:
            name: opa-jwt-policies

---
apiVersion: v1
kind: Service
metadata:
  name: opa-ext-authz
  namespace: gateway
  labels:
    app: opa-ext-authz
spec:
  selector:
    app: opa-ext-authz
  ports:
    - name: grpc
      port: 9191
      targetPort: 9191
    - name: http
      port: 8181
      targetPort: 8181
  type: ClusterIP

---
# =============================================================================
# AuthorizationPolicy CUSTOM - Solo aplica a /smoke
# =============================================================================
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ext-authz-smoke
  namespace: gateway
spec:
  selector:
    matchLabels:
      app: gateway-public
  action: CUSTOM
  provider:
    name: opa-ext-authz
  rules:
    - to:
        - operation:
            paths:
              - "/smoke"
              - "/smoke/*"

