variable "account" {}
variable "organization" {}
variable "vpc" {}
variable "cluster_name" {}
variable "np_api_key" {}
variable "nrn" {}
variable "tags_selectors" {}
variable "domain_name" {}
variable "aws_region" {}
variable "aws_profile" {}
variable "github_installation_id" {}
variable "github_organization" {}
variable "namespace" {}
variable "cluster_provider" {}
variable "image_tag" {}
variable "cloud_provider" {}
variable "dns_type" {}
variable "use_account_slug" {}
variable "image_pull_secrets" {}
variable "service_template" {}
variable "initial_ingress_path" {}
variable "blue_green_ingress_path" {}
variable "k8s_provider" {}
variable "dns_provider_name" {}
variable "policy" {}
variable "resources" {}